### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by sylentpunk** [Metastem/wikiless#43]
My instance was running for a while, but then suddenly stopped working and I couldn't get it to restart. Decided to reclone the repo and prune the old images and build again, but I'm having some trouble.
Here's what I did:
1: Clone the repo with `git clone https://github.com/Metastem/wikiless`
2: Edit docker-compose.yml, commenting out `image: wikiless:latest` and uncommenting out `build .`, setting version to 3.3 and setting a different port for `wikiless: networks: ports`, as well as setting the port in wikiless.config.
3: Run `docker-compose build`, and then `docker-compose up -d`.

This makes two containers for me:  `wikiless_wikiless_1` and `wikiless_wikiless_redis_1`. The redis one is reported as running fine, but the first one is stuck on restarting.

I'm not very good with docker so I'm probably missing something here. Any help with this is greatly appreciated as I wanna keep providing this alternative for others who need it. It's nice to see that you're keeping the project here after its removal. Thanks for doing that.

**Comment by Metastem** [comment]
> My instance was running for a while, but then suddenly stopped working and I couldn't get it to restart. Decided to reclone the repo and prune the old images and build again, but I'm having some trouble. Here's what I did: 1: Clone the repo with `git clone https://github.com/Metastem/wikiless` 2: Edit docker-compose.yml, commenting out `image: wikiless:latest` and uncommenting out `build .`, setting version to 3.3 and setting a different port for `wikiless: networks: ports`, as well as setting the port in wikiless.config. 3: Run `docker-compose build`, and then `docker-compose up -d`.
> 
> This makes two containers for me: `wikiless_wikiless_1` and `wikiless_wikiless_redis_1`. The redis one is reported as running fine, but the first one is stuck on restarting.
> 
> I'm not very good with docker so I'm probably missing something here. Any help with this is greatly appreciated as I wanna keep providing this alternative for others who need it. It's nice to see that you're keeping the project here after its removal. Thanks for doing that.

I'm trying to figure out on that issue, ans anyone know this and help?

**Comment by twomoses** [comment]
In case this helps, this is what I get after pulling the latest image:
```
> Wikiless@0.1.1 start
> node src/wikiless.js

node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module '../config'
Require stack:
- /wikiless/src/wikiless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/wikiless/src/wikiless.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/wikiless/src/wikiless.js' ]
}
```

**Comment by twomoses** [comment]
Perhaps related to #40 ? There has to be a config.js file...

**Comment by twomoses** [comment]
Yep, I cloned it on my local, renamed `wikiless.config` to `config.js`, and built the image and started it without issue.

**Comment by twomoses** [comment]
PR above says it's being deployed, but I have it running at wikiless.nerdyfam.tech.

**Comment by twomoses** [comment]
Nothing says welcome like an insult. Well done!

**Comment by xbdmHQ** [comment]
> Nothing says welcome like an insult. Well done!

I literally tested for you guys, and re-build it no errors on my side. Theres alot that goes into self-hosting, securing the server (ssh, tls, docker, etc.) then because if the host goes down, and you can't maintain by yourself you just hosting it for no reason until the developer decides to leave codeberg/github

**Comment by xbdmHQ** [comment]
> r

Don't use wikiless.config if your using docker, Add the wikiless.config into enviroment if you need add anything.

**Comment by twomoses** [comment]
Please clean your environment and try again. I quite literally pulled the code with the changes you proposed in #46 _and_ changed the compose file to build instead of using the nonexistent image, and I get failures on multiple machines. If there is something missing that we're not aware of, please be explicit in the instructions. 
```
Error: Cannot find module '../config'
Require stack:
- /wikiless/src/wikiless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/wikiless/src/wikiless.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/wikiless/src/wikiless.js' ]
}
```

**Comment by xbdmHQ** [comment]
Sorry i done the testing myself i was in bed to be honest, I'm waiting for the owner to accept the pull request. See my instances for the up-to-date instances here https://wikiless.whateveritworks.org/about.html https://wikiless.whateveritworks.org

**Comment by acixx** [comment]
@twomoses 
Had the same issue, In addition to commenting out "build ." and commenting in "image: ..." I added 

COPY wikiless.config /wikiless/config

to Dockerfile in line 4 and now it works again.

**Comment by xbdmHQ** [comment]
> @twomoses Had the same issue, In addition to commenting out "build ." and commenting in "image: ..." in docker-compose.yml I added
> 
> `COPY wikiless.config /wikiless/config`
> 
> to Dockerfile in line 4 and now it works again.

Waiting for this guy, @Metastem to pull my request for everyone and i am glad. it worked for ya

**Comment by xbdmHQ** [comment]
> FYI, [the last revision of the Dockerfile](https://github.com/Metastem/wikiless/blob/dccaaf0d138c711de101aa4ba0141562aa1e3f0d/Dockerfile) makes an image much smaller, supposedly more secure, and has less bloat. Either way, like I said at the bottom of #45, the most important part is that the issue gets fixed. 🙂

You don't what your talking about dude, stop flooding the shit. It's fixed already how about you open your eyes and wait until he pull the request or look my pull request and build it again

**Comment by twomoses** [comment]
> You don't what your talking about dude, stop flooding the shit. It's fixed already how about you open your eyes and wait until he pull the request or look my pull request and build it again
> 
> EDIT: Maybe read above the guy and myself said now fixed and works 

Yep, it works. You don't have to be rude about it. The fact that the image is 23% larger with stuff that's not necessary might mean something to some people, even if it doesn't mean anything to you.

**Comment by sylentpunk** [comment]
`COPY wikiless.config /wikiless/config` seems to fix the build issue for me. Now I just need to figure out how to actually get this to run on a different port.. Will update when I can confirm that everything works on my end

**Comment by twomoses** [comment]
> `COPY wikiless.config /wikiless/config` seems to fix the build issue for me. Now I just need to figure out how to actually get this to run on a different port.. Will update when I can confirm that everything works on my end

```
    ports:
      - "127.0.0.1:8180:8080"
```
This is what you're looking for. This specific config tells the container to only listen to requests on that host (localhost). This is good if you're running a reverse proxy, like nginx or traefik, on the same machine as Docker. Remove the IP address if you want it to listen on to external requests on that port. The number before the `:` is the port outside the container that will receive incoming requests. The number after the `:` should not change, as this should match the port the application is listening on.

For instance, if you wanted the container to listen on port 3000 from anywhere, you would configure: 
```
    ports:
      - "3000:8080"
```

**Comment by twomoses** [comment]
If you want to build the image with the domain, you can change that and rebuild it... but that is for setting the desired domain, like `wikiless.example.com`. This can also be set as an environment variable (which was unfortunately removed in one of the PR's, but it should still work). I've not tested the latest set of changes here. Instead, I've forked this repo and taken a different direction to get away from problems like this. 
```
    environment:
      DOMAIN: wikiless.example.com
```
Also, I don't believe wikiless is designed to handle SSL directly. Your reverse proxy should handle that, and requests directly to the container should be plain HTTP.

**Comment by sylentpunk** [comment]
Bingo, finally got it working.
Seriously, thanks a lot for the continued help with this. It's greatly appreciated!

**Comment by twomoses** [comment]
@sylentpunk Glad you got it working!

As for PR #56, continuing to insult the members of your community defeats the purpose and spirit of wikiless and why it exists. Open-Source code is owned by the community, not just one person or set of people. I don't see anything like this PR posted to other repositories hosting wikiless code. I looked because we honestly wanted to start a little closer to the original developer's intentions. We're not looking for "_clout_". I personally don't want to maintain the code at all. That said, we disagree with the recent direction taken here and have chosen a different direction. I made a PR in every attempt to move this repo in said direction, and the maintainers disagreed. Nothing wrong with that. So, those changes instead exist in a fork, and since we're now maintaining that fork, yeah, we put our name on it. This is the way FOSS works. This is why there are hundreds of active distros of Linux, all forked directly or indirectly from the original code. Maintainers here should be proud that someone is forking their code. Instead they call it "_stealing_" and say "_he doesn't know anything about without me or metastem to maintain it_" whatever that means. It's unfortunate to find such a mark on such a helpful and welcoming community built around FOSS.

![image](https://github.com/Metastem/wikiless/assets/86500521/87e403d9-0303-4dd9-991f-bddcedbe2f85)
Conditions
- [x] License and copyright notice
- [x] State changes
- [x] Disclose source
- [x] Same license

We have met the conditions of the license and plan on leaving that fork linked to this repo so that anyone who sees the source sees that it is a fork of this repo. That's even the first external link in the README. Say what you want about us, but our intentions are just to provide wikiless in a way that, in our opinion, better suits end users / self hosters. We're not interested in maintaining a list of wikiless instances; that's done very well here (I'm personally offended that you feel like we shouldn't host it just because we disagree with you, but so be it). In fact, we'll link to the README here for a list of wikiless instances, even if that doesn't include us, because, once again, we're not interested in maintaining that.

As for the REDIS error, feel free to open an issue with steps to replicate. I'd be happy to help!
